name: Contionuous_Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install 


  check_npm:
    runs-on: ubuntu-latest  
    steps:
      - name: check npm
        run: npm -v